### ISSUE TITLE
Spider: Pressing "del" deletes (hides?) the selected card 

### ISSUE THREAD

**Issue by gus-massa** [racket/games#11]
Steps to reproduce:

1) Open Spider
2) Use the mouse to select a card
3) Press "delete" or "backspace" in the keyboard
4) The card disappears! (Perhaps it's only hidden or invisible.)
5) You can select and delete more cards.
6) Press the pile of unused card at the top left to deal a new row of cards.
7) The new card in the column of the deleted card is placed in the correct position, leaving some space for the ghost card.

I couldn't' find the handler for the keyboard. I guess this behavior is inherited.

**Comment by rfindler** [comment]
Probably there are a missing `can-insert?` and `can-delete?` callbacks on the `pasteboard%`.

**Comment by gus-massa** [comment]
I tried the other cards games and most off them have the same problem. 

I tried adding the trivial solution, to add

    (define/augment (can-delete? s)
      #f)

near [cards/classes.rkt#L370-L373](https://github.com/racket/games/blob/master/cards/classes.rkt#L370-L373) but it makes the cards live forever. You can't reset the game. Adding (the wrong trivial version of) `can-insert?` is worst because the cards never appear.

**Comment by mflatt** [comment]
I think the right change is probably to override `on-default-char` to do nothing, and I'll try that. That will disable the delete key – and also the arrow keys, which turn out to be able to move the cards around, and that's not supposed to happen.

Also, I need to fix the documentation for `pasteboard%` since `on-default-char` is overridden and does something.
